//==================================================
// This file contains the Excluded objects
// Generated By User: xq
// Format Version: 2
// Date: Wed Apr 29 18:14:05 2026
// ExclMode: default
//==================================================
CHECKSUM: "1868408875 2195414153"
INSTANCE: axi_lite_slave_v1_0_S00_AXI
Block 38 "2575261777" "slv_reg0 <= slv_reg0;"
CHECKSUM: "1868408875 342444530"
INSTANCE: axi_lite_slave_v1_0_S00_AXI
Condition 1 "2000380367" "(((~axi_awready)) && S_AXI_AWVALID && S_AXI_WVALID && aw_en) 1 -1" (1 "0111")
Condition 1 "2000380367" "(((~axi_awready)) && S_AXI_AWVALID && S_AXI_WVALID && aw_en) 1 -1" (4 "1110")
Condition 5 "27613126" "(axi_awready && S_AXI_AWVALID && ((~axi_bvalid)) && axi_wready && S_AXI_WVALID) 1 -1" (1 "01111")
Condition 5 "27613126" "(axi_awready && S_AXI_AWVALID && ((~axi_bvalid)) && axi_wready && S_AXI_WVALID) 1 -1" (5 "11110")
Condition 5 "27613126" "(axi_awready && S_AXI_AWVALID && ((~axi_bvalid)) && axi_wready && S_AXI_WVALID) 1 -1" (4 "11101")
Condition 5 "27613126" "(axi_awready && S_AXI_AWVALID && ((~axi_bvalid)) && axi_wready && S_AXI_WVALID) 1 -1" (3 "11011")
Condition 5 "27613126" "(axi_awready && S_AXI_AWVALID && ((~axi_bvalid)) && axi_wready && S_AXI_WVALID) 1 -1" (2 "10111")
Condition 8 "2222950154" "(axi_arready && S_AXI_ARVALID && ((~axi_rvalid))) 1 -1" (2 "101")
Condition 8 "2222950154" "(axi_arready && S_AXI_ARVALID && ((~axi_rvalid))) 1 -1" (3 "110")
Condition 4 "1886738352" "(((~axi_wready)) && S_AXI_WVALID && S_AXI_AWVALID && aw_en) 1 -1" (1 "0111")
Condition 4 "1886738352" "(((~axi_wready)) && S_AXI_WVALID && S_AXI_AWVALID && aw_en) 1 -1" (4 "1110")
Condition 3 "2000380367" "(((~axi_awready)) && S_AXI_AWVALID && S_AXI_WVALID && aw_en) 1 -1" (1 "0111")
Condition 3 "2000380367" "(((~axi_awready)) && S_AXI_AWVALID && S_AXI_WVALID && aw_en) 1 -1" (4 "1110")
Condition 10 "3747141299" "(axi_wready && S_AXI_WVALID && axi_awready && S_AXI_AWVALID) 1 -1" (1 "0111")
Condition 10 "3747141299" "(axi_wready && S_AXI_WVALID && axi_awready && S_AXI_AWVALID) 1 -1" (4 "1110")
Condition 10 "3747141299" "(axi_wready && S_AXI_WVALID && axi_awready && S_AXI_AWVALID) 1 -1" (3 "1101")
Condition 10 "3747141299" "(axi_wready && S_AXI_WVALID && axi_awready && S_AXI_AWVALID) 1 -1" (2 "1011")
